[package]
name = "EverythingDB"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx         = { version = "0.9.0", features = ["postgres", "runtime-tokio", "chrono", "rust_decimal", "sqlx-toml"] }
serde        = { version = "1.0.229", features = ["derive"] }
chrono       = { version = "0.4.45", features = ["serde"] }
tokio        = { version = "1.53.1", features = ["full"] }
serde_json   = { version = "1.0.151" }
rust_decimal = { version = "1.42.1"} 
dotenvy      = {version = "0.15.7" }
isolang      = { version = "2.4.0" }